### ISSUE TITLE
Consider encouraging investment in evidence over speculation

### ISSUE THREAD

**Issue by RByers** [w3ctag/societal-impact-questionnaire#7]
I love the intent of this initiative, thank you! I do worry, however, that some of these questions ask people to do a lot of speculation that we are generally bad at doing accurately and coming to any agreements around. One way I've personally tried to tackle this from within the Chrome team is by asking folks to try to come to an agreement on what bad outcomes they want to avoid and then make commitments around how they will invest in measuring the extent to which they're occurring, with some ideas about mitigation tactics they could take to shift the balance away from the bad outcomes as necessary.

You're obviously talking about very deep and important questions here to which nobody will have full answers, so I know I'm risking trivializing it, but for the sake of discussion I'll mention some examples I consider similar. First, balancing the harms and benefits of making breaking changes to the web platform as long been a source of heated debate in the web community. With Chrome [exposing our UseCounter data publicly](https://chromestatus.com/metrics/feature/popularity) I believe we've been able to help elevate that debate to be more informed by data in a way that has led to tradeoffs being made that are better for users and developers. Secondly, I believe we missed an opportunity to proactively apply such thinking to mitigate [push permission abuse](https://blog.chromium.org/2020/10/reducing-abusive-notification-content.html) and figured it out only years later after the problem had gotten very bad.

This is a super deep and nuanced topics and I'm sorry I don't have more time right now to make detailed, specific suggestions. But @torgo suggested that I at least file an issue to get the conversation started in this direction. At some later point I'd be happy to help brainstorm some specific things we could do, including the sorts of data Chrome might be willing to collect and share publicly in order to help better inform open debate on these topics.

**Comment by sideshowtom** [comment]
I'm just an amateur smartypants, and not a w3c member, so this is just fwiw.

"In the anticipated symbiotic partnership, men (okay now its people) will set the goals, formulate the hypotheses, determine the criteria, and perform the evaluations. Computing machines will do the routinizable work that must be done to prepare the way for insights and decisions in technical and scientific thinking."

-from https://groups.csail.mit.edu/medg/people/psz/Licklider.html

There is some kind of boundary described there that is worth preserving.  Or is it?  I guess to me, questions about that are the first ones to ask about the goals of a computer project.  And since a lot of those questions and answers would be similar across projects, it makes sense to me to put those questions to and get the answers from the broadest possible audience, and to me that means *not one put together by a public/private partnership, but one put together by a purely public body, under democratic oversight*.  Crickets, I know.

**Comment by torgo** [comment]
@sideshowtom we're not really clear on what your feedback is. Please keep in mind this document we are trying to build is for web standards spec authors so we are trying to focus on that domain rather than the wider picture. If you have specific feedback on the doc, please feel free to open another issue. However I think we're going to keep this issue focused on Rick's feedback.

**Comment by torgo** [comment]
@RByers we're just picking this up at our f2f - Amy is going to do a PR that will try to capture some of these ideas.

**Comment by torgo** [comment]
Hi @RByers we picked this up again at our virtual f2f this week and wrote some text to try to address this issue- see https://w3ctag.github.io/societal-impact-questionnaire/#questions. Let us know what you think and maybe we can close this issue, or please feel free to suggest changes.

**Comment by torgo** [comment]
Closed as addressed in #8.
